In [49]:
import pandas as pd

In [50]:
jk=pd.read_csv("/content/retail_store_sales_dataset.csv")

In [51]:
jk.head()

,transaction_id,city,store,product_category,product_name,unit_price,quantity,customer_type,payment_method,discount_percent,total_sale,discount_amount,final_amount
0,5001,Pune,Central Mall,Home Decor,Face Cream,2386,4,Returning,Card,15,9544,1431.60,8112.40
1,5002,Bangalore,City Center,Home Decor,Wall Lamp,1383,1,New,Card,10,1383,138.30,1244.70
2,5003,Hyderabad,Central Mall,Clothing,Jeans,4937,1,Returning,UPI,5,4937,246.85,4690.15
3,5004,Hyderabad,Smart Bazaar,Home Decor,Mixer,1470,2,Returning,UPI,10,2940,294.00,2646.00
4,5005,Hyderabad,Central Mall,Beauty,Headphones,2688,1,New,Cash,10,2688,268.80,2419.20

In [52]:
jk.tail()

,transaction_id,city,store,product_category,product_name,unit_price,quantity,customer_type,payment_method,discount_percent,total_sale,discount_amount,final_amount
215,5216,Hyderabad,Smart Bazaar,Home Decor,Jeans,1809,3,New,Card,15,5427,814.05,4612.95
216,5217,Mysore,Urban Retail,Beauty,Rice Bag,4696,1,Returning,Cash,15,4696,704.40,3991.60
217,5218,Pune,Smart Bazaar,Electronics,Jeans,3699,4,New,Cash,0,14796,0.00,14796.00
218,5219,Chennai,Urban Retail,Groceries,T-shirt,2845,4,New,UPI,15,11380,1707.00,9673.00
219,5220,Chennai,Central Mall,Home Decor,Headphones,2783,1,Returning,Card,10,2783,278.30,2504.70

In [53]:
jk.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 220 entries, 0 to 219
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    220 non-null    int64
 1   city              220 non-null    object
 2   store             220 non-null    object
 3   product_category  220 non-null    object
 4   product_name      220 non-null    object
 5   unit_price        220 non-null    int64
 6   quantity          220 non-null    int64
 7   customer_type     220 non-null    object
 8   payment_method    220 non-null    object
 9   discount_percent  220 non-null    int64
 10  total_sale        220 non-null    int64
 11  discount_amount   220 non-null    float64
 12  final_amount      220 non-null    float64
dtypes: float64(2), int64(5), object(6)
memory usage: 22.5+ KB

In [54]:
jk.shape

(220, 13)

In [55]:
jk["city"].unique()

array(['Pune', 'Bangalore', 'Hyderabad', 'Mysore', 'Chennai'],
      dtype=object)

In [56]:
jk["product_category"].unique()

array(['Home Decor', 'Clothing', 'Beauty', 'Electronics', 'Groceries'],
      dtype=object)

In [57]:
len(jk["product_category"].unique())

5

In [58]:
jk.head(10)

,transaction_id,city,store,product_category,product_name,unit_price,quantity,customer_type,payment_method,discount_percent,total_sale,discount_amount,final_amount
0,5001,Pune,Central Mall,Home Decor,Face Cream,2386,4,Returning,Card,15,9544,1431.60,8112.40
1,5002,Bangalore,City Center,Home Decor,Wall Lamp,1383,1,New,Card,10,1383,138.30,1244.70
2,5003,Hyderabad,Central Mall,Clothing,Jeans,4937,1,Returning,UPI,5,4937,246.85,4690.15
3,5004,Hyderabad,Smart Bazaar,Home Decor,Mixer,1470,2,Returning,UPI,10,2940,294.00,2646.00
4,5005,Hyderabad,Central Mall,Beauty,Headphones,2688,1,New,Cash,10,2688,268.80,2419.20
5,5006,Mysore,Urban Retail,Electronics,Rice Bag,1652,4,Returning,UPI,0,6608,0.00,6608.00
6,5007,Hyderabad,Metro Mart,Home Decor,Wall Lamp,2739,2,New,Card,15,5478,821.70,4656.30
7,5008,Chennai,Central Mall,Electronics,Mixer,3899,3,New,Cash,15,11697,1754.55,9942.45
8,5009,Pune,Central Mall,Electronics,Wall Lamp,4628,3,Returning,UPI,10,13884,1388.40,12495.60
9,5010,Bangalore,City Center,Home Decor,Wall Lamp,2414,4,Returning,Card,5,9656,482.80,9173.20

In [59]:
jk.describe()

,transaction_id,unit_price,quantity,discount_percent,total_sale,discount_amount,final_amount
count,220.000000,220.000000,220.000000,220.000000,220.000000,220.000000,220.000000
mean,5110.500000,2608.868182,2.418182,10.181818,6209.959091,628.017045,5581.942045
std,63.652704,1333.082940,1.133805,6.652746,4602.416562,676.102942,4205.370713
min,5001.000000,228.000000,1.000000,0.000000,229.000000,0.000000,183.200000
25%,5055.750000,1470.750000,1.000000,5.000000,2690.250000,142.912500,2395.125000
50%,5110.500000,2655.000000,2.000000,10.000000,4526.000000,400.500000,3991.175000
75%,5165.250000,3639.750000,3.000000,15.000000,9413.500000,870.650000,8231.625000
max,5220.000000,4995.000000,4.000000,20.000000,19900.000000,2997.000000,19900.000000

In [60]:
jk["product_category"].unique()

array(['Home Decor', 'Clothing', 'Beauty', 'Electronics', 'Groceries'],
      dtype=object)

In [61]:
jk["product_category"].value_counts().idxmax()

'Groceries'

In [62]:
jk.groupby("product_category")["quantity"].sum().idxmax()

'Groceries'

In [63]:
jk.groupby("store")["total_sale"].sum().idxmax()

'Smart Bazaar'

In [64]:
jk["payment_method"].max()

'UPI'

In [65]:
jk["city"].value_counts().idxmax()

'Hyderabad'

In [66]:
jk["final_amount"].mean()

np.float64(5581.942045454545)

In [67]:
jk["total_sale"].max()

19900

In [68]:
jk.groupby("city")["final_amount"].sum().idxmax()

'Hyderabad'

In [69]:
jk["payment_method"].max()

'UPI'

In [70]:
jk.groupby("customer_type")["final_amount"].sum()

customer_type
New          671836.35
Returning    556190.90
Name: final_amount, dtype: float64

In [71]:
jk["payment_method"].value_counts().idxmax()

'Card'

In [72]:
jk.groupby("customer_type")["final_amount"].sum().idxmax()

'New'

In [73]:
jk.groupby("product_category")["final_amount"].sum().idxmax()

'Groceries'

In [74]:
jk.groupby("store")["discount_amount"].sum().idxmax()

'Smart Bazaar'

In [75]:
jk["product_name"].value_counts().idxmax()

'Mixer'

In [76]:
jk.groupby("city")["final_amount"].max()

city
Bangalore    15249.0
Chennai      19000.0
Hyderabad    16580.0
Mysore       19900.0
Pune         17474.4
Name: final_amount, dtype: float64

In [77]:
# Which product sells the most units?
jk.groupby("product_category")["final_amount"].max()

product_category
Beauty         16580.0
Clothing       17474.4
Electronics    19900.0
Groceries      12988.8
Home Decor     19000.0
Name: final_amount, dtype: float64

In [78]:
# Which city has the highest average purchase value?
jk.groupby("city")["final_amount"].mean().idxmax()

'Mysore'

In [79]:
# Which product category is most popular among returning customers?
cu_Returning=jk[jk["customer_type"]=="Returning"]
cu_Returning['customer_type']

0      Returning
2      Returning
3      Returning
5      Returning
8      Returning
         ...
211    Returning
212    Returning
213    Returning
216    Returning
219    Returning
Name: customer_type, Length: 114, dtype: object

In [80]:
# Which product category is most popular among returning customers?
cu_Returning.groupby("product_category")["customer_type"].sum().idxmax()

'Groceries'

In [81]:
# Which product category is most popular among returning customers?
cu_Returning["product_category"].value_counts().idxmax()

'Groceries'

In [82]:
jk.head()

,transaction_id,city,store,product_category,product_name,unit_price,quantity,customer_type,payment_method,discount_percent,total_sale,discount_amount,final_amount
0,5001,Pune,Central Mall,Home Decor,Face Cream,2386,4,Returning,Card,15,9544,1431.60,8112.40
1,5002,Bangalore,City Center,Home Decor,Wall Lamp,1383,1,New,Card,10,1383,138.30,1244.70
2,5003,Hyderabad,Central Mall,Clothing,Jeans,4937,1,Returning,UPI,5,4937,246.85,4690.15
3,5004,Hyderabad,Smart Bazaar,Home Decor,Mixer,1470,2,Returning,UPI,10,2940,294.00,2646.00
4,5005,Hyderabad,Central Mall,Beauty,Headphones,2688,1,New,Cash,10,2688,268.80,2419.20