In [49]:
# NUMPY- NUMERICAL PYTHON
import numpy as np
import pandas as pd

In [50]:
df=pd.read_csv("/content/swiggy_orders_dataset (1) (1).csv")

In [51]:
a=[1,2,3,4,56]
np.sum(a)

np.int64(66)

In [52]:
np.mean(a)

np.float64(13.2)

In [53]:
np.min(a)

np.int64(1)

In [54]:
np.argmax(a)

np.int64(4)

In [55]:
np.max(a)

np.int64(56)

In [56]:
np.cumsum(a)

array([ 1,  3,  6, 10, 66])

In [57]:
a

[1, 2, 3, 4, 56]

In [58]:
# data creation- creating array

a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [59]:
type(a)

numpy.ndarray

In [60]:
a=[1,2,3,4,5,6,7,8]
type(a)

list

In [61]:
a_np = np.array(a)
a_np.ndim

1

In [62]:
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
b.ndim

2

In [64]:
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [65]:
c.ndim

3

In [66]:
c=np.array([[[1,2,3],[4,5,6] , [1,2,3],[4,5,6]]])
c

array([[[1, 2, 3],
        [4, 5, 6],
        [1, 2, 3],
        [4, 5, 6]]])

In [67]:
b.shape

(3, 3)

In [68]:
c.shape

(1, 4, 3)

In [69]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [70]:
a=np.arange(200,300)
a

array([200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212,
       213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225,
       226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238,
       239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251,
       252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264,
       265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277,
       278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290,
       291, 292, 293, 294, 295, 296, 297, 298, 299])

In [71]:
np.arange(200,300,dtype=float)

array([200., 201., 202., 203., 204., 205., 206., 207., 208., 209., 210.,
       211., 212., 213., 214., 215., 216., 217., 218., 219., 220., 221.,
       222., 223., 224., 225., 226., 227., 228., 229., 230., 231., 232.,
       233., 234., 235., 236., 237., 238., 239., 240., 241., 242., 243.,
       244., 245., 246., 247., 248., 249., 250., 251., 252., 253., 254.,
       255., 256., 257., 258., 259., 260., 261., 262., 263., 264., 265.,
       266., 267., 268., 269., 270., 271., 272., 273., 274., 275., 276.,
       277., 278., 279., 280., 281., 282., 283., 284., 285., 286., 287.,
       288., 289., 290., 291., 292., 293., 294., 295., 296., 297., 298.,
       299.])

In [72]:
a.size

100

In [73]:
b=a.reshape(2,2,25)

In [74]:
b.ndim

3

In [75]:
b

array([[[200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211,
         212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223,
         224],
        [225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236,
         237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248,
         249]],

       [[250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261,
         262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273,
         274],
        [275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286,
         287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298,
         299]]])

In [76]:
c=b

In [77]:
c=b.flatten()

In [78]:
b.ravel()

array([200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212,
       213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225,
       226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238,
       239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251,
       252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264,
       265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277,
       278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290,
       291, 292, 293, 294, 295, 296, 297, 298, 299])

In [79]:
import pandas as pd

In [80]:
a=[1,2,3,4]

In [81]:
type(a)

list

In [82]:
pd.Series(a,index=['a','b','c','d'])

a    1
b    2
c    3
d    4
dtype: int64

In [83]:
d={"sl_no":[1,2,3,4],
   "name":["abhi","bharat","chethan","dhanush"]}
d

{'sl_no': [1, 2, 3, 4], 'name': ['abhi', 'bharat', 'chethan', 'dhanush']}

In [84]:
d.values()

dict_values([[1, 2, 3, 4], ['abhi', 'bharat', 'chethan', 'dhanush']])

In [85]:
pd.DataFrame(d, index=["A","B","C","D"])

   sl_no     name
A      1     abhi
B      2   bharat
C      3  chethan
D      4  dhanush

In [86]:
pd.DataFrame(d, index=["A","B","C","D"],columns=["roll numbers"])

  roll numbers
A          NaN
B          NaN
C          NaN
D          NaN

In [87]:
import pandas as pd
df=pd.read_csv("/content/swiggy_orders_dataset (1) (1).csv")

In [88]:
df.head()

,order_id,city,product,price,quantity,delivery_time_min,payment_method,customer_type,revenue
0,100001,Davangere,Pizza,123,4,53,Wallet,Returning,492
1,100002,Hubli,Pasta,155,4,36,UPI,New,620
2,100003,Belgaum,Burger,297,2,43,UPI,New,594
3,100004,Davangere,Pizza,376,2,60,UPI,Returning,752
4,100005,Mangalore,Pizza,136,2,24,Card,Returning,272

In [89]:
df.tail()

,order_id,city,product,price,quantity,delivery_time_min,payment_method,customer_type,revenue
9995,109996,Mangalore,Dosa,227,2,48,Wallet,Returning,454
9996,109997,Belgaum,Pasta,266,2,46,Card,New,532
9997,109998,Mysore,Dosa,295,2,23,Wallet,Returning,590
9998,109999,Mangalore,Sandwich,495,5,55,Wallet,New,2475
9999,110000,Mysore,Burger,308,5,62,UPI,Returning,1540

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   order_id           10000 non-null  int64
 1   city               10000 non-null  object
 2   product            10000 non-null  object
 3   price              10000 non-null  int64
 4   quantity           10000 non-null  int64
 5   delivery_time_min  10000 non-null  int64
 6   payment_method     10000 non-null  object
 7   customer_type      10000 non-null  object
 8   revenue            10000 non-null  int64
dtypes: int64(5), object(4)
memory usage: 703.3+ KB

In [91]:
df.describe()

,order_id,price,quantity,delivery_time_min,revenue
count,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000
mean,105000.50000,308.503000,3.052400,39.420700,939.880300
std,2886.89568,109.617244,1.424309,14.382733,571.020438
min,100001.00000,120.000000,1.000000,15.000000,120.000000
25%,102500.75000,213.000000,2.000000,27.000000,462.000000
50%,105000.50000,308.000000,3.000000,40.000000,830.000000
75%,107500.25000,404.000000,4.000000,52.000000,1315.000000
max,110000.00000,499.000000,5.000000,64.000000,2495.000000

In [92]:
df["city"].unique()

array(['Davangere', 'Hubli', 'Belgaum', 'Mangalore', 'Mysore', 'Tumkur',
       'Bangalore'], dtype=object)

In [93]:
df["city"].nunique()

7

In [94]:
df["city"].value_counts()

city
Belgaum      1464
Hubli        1439
Davangere    1429
Mysore       1428
Tumkur       1426
Bangalore    1423
Mangalore    1391
Name: count, dtype: int64

In [95]:
df["city"].value_counts().idxmax()

'Belgaum'

In [96]:
df["city"].value_counts(normalize=True)

city
Belgaum      0.1464
Hubli        0.1439
Davangere    0.1429
Mysore       0.1428
Tumkur       0.1426
Bangalore    0.1423
Mangalore    0.1391
Name: proportion, dtype: float64

In [97]:
df["city"].unique()

array(['Davangere', 'Hubli', 'Belgaum', 'Mangalore', 'Mysore', 'Tumkur',
       'Bangalore'], dtype=object)

In [98]:
df["product"].value_counts()

product
Burger        1275
Noodles       1274
Pizza         1265
Fried Rice    1264
Pasta         1253
Dosa          1251
Sandwich      1221
Biryani       1197
Name: count, dtype: int64

In [99]:
df["product"].value_counts().idxmax()

'Burger'

In [100]:
df["price"].mean()

np.float64(308.503)

In [101]:
df["price"].max()

499

In [102]:

df.groupby("product")["revenue"].sum()

product
Biryani       1145968
Burger        1181994
Dosa          1159543
Fried Rice    1198050
Noodles       1147403
Pasta         1206162
Pizza         1179411
Sandwich      1180272
Name: revenue, dtype: int64

In [103]:
df["delivery_time_min"].max()

64

In [104]:
# wht r the payment method mode are there
df["payment_method"].unique()

array(['Wallet', 'UPI', 'Card', 'Cash'], dtype=object)

In [105]:
# which payment method is used alot
df["payment_method"].max()

'Wallet'

In [106]:
df.head()

,order_id,city,product,price,quantity,delivery_time_min,payment_method,customer_type,revenue
0,100001,Davangere,Pizza,123,4,53,Wallet,Returning,492
1,100002,Hubli,Pasta,155,4,36,UPI,New,620
2,100003,Belgaum,Burger,297,2,43,UPI,New,594
3,100004,Davangere,Pizza,376,2,60,UPI,Returning,752
4,100005,Mangalore,Pizza,136,2,24,Card,Returning,272

In [107]:
# which customer type is maximum
df["customer_type"].max()

'Returning'

In [108]:
# which customer type is high
df.groupby("customer_type")["revenue"].sum()

customer_type
New          4747905
Returning    4650898
Name: revenue, dtype: int64

In [109]:
df.drop("revenue",axis=1,inplace=True)

In [110]:
df.head()

,order_id,city,product,price,quantity,delivery_time_min,payment_method,customer_type
0,100001,Davangere,Pizza,123,4,53,Wallet,Returning
1,100002,Hubli,Pasta,155,4,36,UPI,New
2,100003,Belgaum,Burger,297,2,43,UPI,New
3,100004,Davangere,Pizza,376,2,60,UPI,Returning
4,100005,Mangalore,Pizza,136,2,24,Card,Returning

In [111]:
df["revenue"]=df["price"]*df["quantity"]

In [112]:
df.head()

,order_id,city,product,price,quantity,delivery_time_min,payment_method,customer_type,revenue
0,100001,Davangere,Pizza,123,4,53,Wallet,Returning,492
1,100002,Hubli,Pasta,155,4,36,UPI,New,620
2,100003,Belgaum,Burger,297,2,43,UPI,New,594
3,100004,Davangere,Pizza,376,2,60,UPI,Returning,752
4,100005,Mangalore,Pizza,136,2,24,Card,Returning,272

In [113]:
import matplotlib.pyplot as plt
import seaborn as sns